---
- name: Ensure inbound mail cronjob
  cron:
    name: inbound mail
    user: "{{ redmine_username }}"
    minute: "*/{{ redmine_mail_pop3_refresh_minutes }}"
    job: >
      cd {{ redmine_source_path }} &&
      {{ redmine_source_path }}/bin/rake
      redmine:email:receive_pop3
      RAILS_ENV={{ redmine_rails_environment }}
      host="{{ redmine_mail_pop3_host }}"
      port="{{ redmine_mail_pop3_port }}"
      username="{{ redmine_mail_pop3_username }}"
      password="{{ redmine_mail_pop3_password }}"
      apop={{ redmine_mail_pop3_apop|bool()|lower }}
      ssl={{ redmine_mail_pop3_ssl|bool()|lower }}
      >> /dev/null
  when: redmine_mail_pop3_enable
