---
- include: tasks/init.yml
  become_user: root
  become: true

- include: tasks/database.yml
  become_user: postgres
  become: true

- include: tasks/cron.yml
  become_user: "{{ redmine_username }}"
  become: true

- include: tasks/source.yml
  become_user: "{{ redmine_username }}"
  become: true

- include: tasks/aux.yml
  become_user: "{{ redmine_username }}"
  become: true

- include: tasks/deps.yml
  become_user: "{{ redmine_username }}"
  become: true

- include: tasks/config.yml
  become_user: "{{ redmine_username }}"
  become: true

- include: tasks/finish.yml
  become_user: "{{ redmine_username }}"
  become: true
